### ISSUE TITLE
GCC 5.4(32-bits) complains when using "%lu" with a variable which is not "long unsigned int"

### ISSUE THREAD

**Issue by liuqun** [intel/tpm2-abrmd#301]
https://github.com/intel/tpm2-abrmd/blob/333824b5be1b5d39522491cfe38829ada01f70b3/src/tcti-tabrmd.c#L541-L546

```
In file included from /usr/include/glib-2.0/glib.h:62:0,
                 from /usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/include/glib-2.0/glib-object.h:23,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from src/tcti-tabrmd.c:29:
src/tcti-tabrmd.c: In function ‘tabrmd_bus_type_from_str’:
src/tcti-tabrmd.c:546:14: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘unsigned int’ [-Werror=format=]
     g_debug ("BUS_NAME_TYPE_MAP_LENGTH: %lu", BUS_NAME_TYPE_MAP_LENGTH);
              ^
/usr/include/glib-2.0/glib/gmessages.h:170:32: note: in definition of macro ‘g_debug’
                                __VA_ARGS__)
                                ^
cc1: all warnings being treated as errors
```

I guess that **size_t** was defined as **unsigned int** on 32-bit architecture(arm and x86), but defined as **long unsigned int** on x86_64 architecture.

We may cast BUS_NAME_TYPE_MAP_LENGTH from `size_t` into `long unsigned int`:
```
#define BUS_NAME_TYPE_MAP_LENGTH \
    ((long unsigned int) (sizeof (bus_name_type_map) / sizeof (bus_name_type_entry_t)))

void foobar()
{
    g_debug ("BUS_NAME_TYPE_MAP_LENGTH: %lu", BUS_NAME_TYPE_MAP_LENGTH);
}
```

Casting BUS_NAME_TYPE_MAP_LENGTH into **int** also works for me:
```
#define BUS_NAME_TYPE_MAP_LENGTH \
    ((int) (sizeof (bus_name_type_map) / sizeof (bus_name_type_entry_t)))

void foobar()
{
    g_debug ("BUS_NAME_TYPE_MAP_LENGTH: %d", (int) BUS_NAME_TYPE_MAP_LENGTH);
}
```

---

```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/5/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.5' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-armhf/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-armhf --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-armhf --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --enable-multilib --disable-sjlj-exceptions --with-arch=armv7-a --with-fpu=vfpv3-d16 --with-float=hard --with-mode=thumb --disable-werror --enable-multilib --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.5) 
```

**Comment by twoerner** [comment]
same thing occurs with OE master (gcc 7.2):

| ../tpm2-abrmd/src/tcti-tabrmd.c:546:14: error: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'unsigned int' [-Werror=format=]
|      g_debug ("BUS_NAME_TYPE_MAP_LENGTH: %lu", BUS_NAME_TYPE_MAP_LENGTH);

caused by commit 0a3f1601

**Comment by flihp** [comment]
Good catch. Thanks for the extra data @twoerner, made finding the issue super easy. PR incoming ...

**Comment by flihp** [comment]
should be fixed by #304

**Comment by twoerner** [comment]
Yep, succeeds for me, thanks!
👍
